set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

set -g @themepack 'powerline/default/purple'

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind _ split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file $HOME/.tmux.conf

unbind down
unbind up
unbind right
unbind left
bind -r down resize-pane -D 5
bind -r up resize-pane -U 5
bind -r right resize-pane -R 5
bind -r left resize-pane -L 5

set -g mouse on

run '~/.tmux/plugins/tpm/tpm'
