enable_background_blur yes
background_opacity 0.7
background_blur 1

font_family      Hack Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

cursor_shape block
shell_integration no-cursor
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0.5
cursor_stop_blinking_after 15.0
cursor_trail 200
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2

scrollback_lines 2000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 0

mouse_hide_wait 3.0
url_style curly
open_url_with default
copy_on_select no
strip_trailing_spaces never

repaint_delay 10
input_delay 3
sync_to_monitor yes

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell yes
bell_on_tab yes

confirm_os_window_close 0
remember_window_size  yes
initial_window_width  640
initial_window_height 400
window_resize_step_cells 2
window_resize_step_lines 2
window_border_width 1pt
draw_minimal_borders yes
window_margin_width 0
single_window_margin_width -1
window_padding_width 4
placement_strategy center

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_min_tabs 2
tab_switch_strategy previous
tab_fade 0.25 0.5 0.75 1
tab_separator " ┇"
tab_title_template {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# The basic colors

foreground                      #ffffff
background                      #181818
selection_foreground            #181818 
selection_background            #ffffff


# Cursor colors

cursor                          #ffffff
cursor_text_color               #000000


# URL underline color when hovering with mouse

url_color                       #d4d4d4


# kitty window border colors and terminal bell colors

active_border_color             #000000
inactive_border_color           #000000
bell_border_color               #ffffff
visual_bell_color               none


# OS Window titlebar colors

wayland_titlebar_color          system
macos_titlebar_color            system


# Tab bar colors

active_tab_foreground           #ffffff
active_tab_background           #000000
inactive_tab_foreground         #b9b9b9
inactive_tab_background         #000000
tab_bar_background              none
tab_bar_margin_color            none


# Colors for marks (marked text in the terminal)

mark1_foreground #000000
mark1_background #ffffff
mark2_foreground #000000
mark2_background #d4d4d4
mark3_foreground #000000
mark3_background #b9b9b9


# The basic 16 colors

# black
color0 #282828
color8 #3c3c3c

# red
color1 #a35b5b
color9 #c17d7d

# green
color2  #7f9f7f
color10 #a0c0a0

# yellow
color3  #bfa97a
color11 #d9c497

# blue
color4  #6f8fae
color12 #8fb0d0

# magenta
color5  #9f7fac
color13 #bfa0cc

# cyan
color6  #7aa3a3
color14 #99c2c2

# white
color7  #d0d0d0
color15 #f0f0f0
