preload = /home/edgar/dotfiles/wallpapers/lain.jpg #theme:lain
#preload = /home/edgar/dotfiles/wallpapers/gruvbox-wave.png #theme:gruvbox

wallpaper {
	monitor = *
   path = /home/edgar/dotfiles/wallpapers/lain.jpg #theme:lain
#   path = /home/edgar/dotfiles/wallpapers/gruvbox-wave.png #theme:gruvbox
}

splash = false
