#preload = /home/edgar/dotfiles/wallpapers/lain.jpg #theme:lain
#preload = /home/edgar/dotfiles/wallpapers/gruvbox-wave.png #theme:gruvbox
preload = /home/edgar/dotfiles/wallpapers/comp-cats.png #theme:cats

wallpaper {
	monitor = *
#   path = /home/edgar/dotfiles/wallpapers/lain.jpg #theme:lain
#   path = /home/edgar/dotfiles/wallpapers/gruvbox-wave.png #theme:gruvbox
   path = /home/edgar/dotfiles/wallpapers/comp-cats.png #theme:cats
}

splash = false
