#preload = /home/edgar/dotfiles/wallpapers/ascii-wave.png #wallpaper:wave
 preload = /home/edgar/dotfiles/wallpapers/centiped.jpg #wallpaper:centiped
# preload = /home/edgar/dotfiles/wallpapers/eyes.jpg #wallpaper:eyes
# preload = /home/edgar/dotfiles/wallpapers/shinji.jpg #wallpaper:shinji
# preload = /home/edgar/dotfiles/wallpapers/touch-ascii.jpg #wallpaper:touch

wallpaper {
	monitor = *
#    path = /home/edgar/dotfiles/wallpapers/ascii-wave.png #wallpaper:wave
 path = /home/edgar/dotfiles/wallpapers/centiped.jpg #wallpaper:centiped
# path = /home/edgar/dotfiles/wallpapers/eyes.jpg #wallpaper:eyes
# path = /home/edgar/dotfiles/wallpapers/shinji.jpg #wallpaper:shinji
# path = /home/edgar/dotfiles/wallpapers/touch-ascii.jpg #wallpaper:touch
}

splash = false
