preload = /home/edgar/dotfiles/wallpapers/comp-cats.png # walpaper:dark
# preload = /home/edgar/dotfiles/wallpapers/shinji.jpg # wallpaper:light

wallpaper {
	monitor = *
    path = /home/edgar/dotfiles/wallpapers/comp-cats.png # wallpaper:dark
# path = /home/edgar/dotfiles/wallpapers/shinji.jpg # wallpaper:light
}

splash = false
