-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.00", position = "0x0", scale = 1.00 })
hl.monitor({ output = "DP-1", mode = "1920x1080@59.96", position = "1920x0", scale = 1.00 })
