-- Auto-generated by Wox. Do not edit.
-- Hyprland global hotkey bindings for Wox launcher.
if wox_bind_handles then
  for _, bind in ipairs(wox_bind_handles) do bind:set_enabled(false) end
end
wox_bind_handles = {}
table.insert(wox_bind_handles, hl.bind("CTRL + SPACE", hl.dsp.exec_cmd("/usr/bin/wox wox://toggle"), { repeating = false, description = "Wox global hotkey" }))
